"""Allow null speaker_session_role_id in messages

Revision ID: 002
Revises: 001
Create Date: 2024-12-04 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'speaker_session_role_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'speaker_session_role_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###