"""Add topic field to flow_templates and logic_config to flow_steps

Revision ID: 281ca6b9ad00
Revises: 
Create Date: 2025-12-03 16:36:03.455805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281ca6b9ad00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loop_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('condition_config', sa.Text(), nullable=True))

    with op.batch_alter_table('flow_templates', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flow_templates', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('flow_steps', schema=None) as batch_op:
        batch_op.drop_column('condition_config')
        batch_op.drop_column('loop_config')

    # ### end Alembic commands ###
