"""Update flow models to match frontend interface

Revision ID: update_flow_models
Revises: 281ca6b9ad00
Create Date: 2025-12-03 21:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'update_flow_models'
down_revision = '281ca6b9ad00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # FlowTemplate表结构更新
    with op.batch_alter_table('flow_templates') as batch_op:
        # 将version字段改为可选，移除默认值
        batch_op.alter_column('version',
                           existing_type=sa.VARCHAR(length=20),
                           nullable=True,
                           server_default=None)

        # 将is_active字段改为可选，移除默认值
        batch_op.alter_column('is_active',
                           existing_type=sa.BOOLEAN(),
                           nullable=True,
                           server_default=None)

        # 确保termination_config字段为可选
        batch_op.alter_column('termination_config',
                           existing_type=sa.TEXT(),
                           nullable=True,
                           server_default=None)

    # FlowStep表结构更新
    with op.batch_alter_table('flow_steps') as batch_op:
        # 确保target_role_ref字段为可选
        batch_op.alter_column('target_role_ref',
                           existing_type=sa.VARCHAR(length=50),
                           nullable=True)

        # 确保context_param字段为可选
        batch_op.alter_column('context_param',
                           existing_type=sa.TEXT(),
                           nullable=True)

        # 确保logic_config字段为可选
        batch_op.alter_column('logic_config',
                           existing_type=sa.TEXT(),
                           nullable=True)

        # 确保next_step_id字段为可选
        batch_op.alter_column('next_step_id',
                           existing_type=sa.INTEGER(),
                           nullable=True)

        # 确保description字段为可选
        batch_op.alter_column('description',
                           existing_type=sa.VARCHAR(length=500),
                           nullable=True)

    # 数据迁移：为null字段设置合理的默认值
    op.execute("""
        UPDATE flow_templates
        SET version = CASE
            WHEN version IS NULL THEN '1.0.0'
            ELSE version
        END
    """)

    op.execute("""
        UPDATE flow_templates
        SET is_active = CASE
            WHEN is_active IS NULL THEN 1
            ELSE is_active
        END
    """)

    # 为现有数据迁移context_scope格式
    op.execute("""
        UPDATE flow_steps
        SET context_scope = CASE
            WHEN context_scope IS NULL OR context_scope = '' THEN 'all'
            ELSE context_scope
        END
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 恢复FlowTemplate表的原始结构
    with op.batch_alter_table('flow_templates') as batch_op:
        batch_op.alter_column('version',
                           existing_type=sa.VARCHAR(length=20),
                           nullable=False,
                           server_default=sa.text("'1.0.0'"))

        batch_op.alter_column('is_active',
                           existing_type=sa.BOOLEAN(),
                           nullable=False,
                           server_default=sa.text('1'))

        batch_op.alter_column('termination_config',
                           existing_type=sa.TEXT(),
                           nullable=False)

    # 恢复FlowStep表的原始结构
    with op.batch_alter_table('flow_steps') as batch_op:
        batch_op.alter_column('target_role_ref',
                           existing_type=sa.VARCHAR(length=50),
                           nullable=False)

        batch_op.alter_column('context_param',
                           existing_type=sa.TEXT(),
                           nullable=False)

        batch_op.alter_column('logic_config',
                           existing_type=sa.TEXT(),
                           nullable=False)

        batch_op.alter_column('next_step_id',
                           existing_type=sa.INTEGER(),
                           nullable=False)

        batch_op.alter_column('description',
                           existing_type=sa.VARCHAR(length=500),
                           nullable=False)